export const beefMeals = [
  {
    strMeal: "Beef and Mustard Pie",
    strMealThumb: 'require("../assets/images/meals/52874.jpg")',
    idMeal: "52874",
  },
  {
    strMeal: "Beef Asado",
    strMealThumb: 'require("../assets/images/meals/53071.jpg")',
    idMeal: "53071",
  },
  {
    strMeal: "Beef Banh Mi Bowls with Sriracha Mayo, Carrot & Pickled Cucumber",
    strMealThumb: 'require("../assets/images/meals/52997.jpg")',
    idMeal: "52997",
  },
  {
    strMeal: "Beef Bourguignon",
    strMealThumb: 'require("../assets/images/meals/52904.jpg")',
    idMeal: "52904",
  },
  {
    strMeal: "Beef Brisket Pot Roast",
    strMealThumb: 'require("../assets/images/meals/52812.jpg")',
    idMeal: "52812",
  },
  {
    strMeal: "Beef Caldereta",
    strMealThumb: 'require("../assets/images/meals/53070.jpg")',
    idMeal: "53070",
  },
  {
    strMeal: "Beef Dumpling Stew",
    strMealThumb: 'require("../assets/images/meals/52873.jpg")',
    idMeal: "52873",
  },
  {
    strMeal: "Beef Lo Mein",
    strMealThumb: 'require("../assets/images/meals/52952.jpg")',
    idMeal: "52952",
  },
  {
    strMeal: "Beef Mechado",
    strMealThumb: 'require("../assets/images/meals/53068.jpg")',
    idMeal: "53068",
  },
  {
    strMeal: "Beef Rendang",
    strMealThumb: 'require("../assets/images/meals/53053.jpg")',
    idMeal: "53053",
  },
  {
    strMeal: "Beef stroganoff",
    strMealThumb: 'require("../assets/images/meals/52834.jpg")',
    idMeal: "52834",
  },
  {
    strMeal: "Beef Sunday Roast",
    strMealThumb: 'require("../assets/images/meals/52824.jpg")',
    idMeal: "52824",
  },
  {
    strMeal: "Beef Wellington",
    strMealThumb: 'require("../assets/images/meals/52803.jpg")',
    idMeal: "52803",
  },
  {
    strMeal: "Big Mac",
    strMealThumb: 'require("../assets/images/meals/53013.jpg")',
    idMeal: "53013",
  },
  {
    strMeal: "Bistek",
    strMealThumb: 'require("../assets/images/meals/53069.jpg")',
    idMeal: "53069",
  },
  {
    strMeal: "Bitterballen (Dutch meatballs)",
    strMealThumb: 'require("../assets/images/meals/52979.jpg")',
    idMeal: "52979",
  },
  {
    strMeal: "Braised Beef Chilli",
    strMealThumb: 'require("../assets/images/meals/52826.jpg")',
    idMeal: "52826",
  },
  {
    strMeal: "Cevapi Sausages",
    strMealThumb: 'require("../assets/images/meals/53055.jpg")',
    idMeal: "53055",
  },
  {
    strMeal: "Chivito uruguayo",
    strMealThumb: 'require("../assets/images/meals/53063.jpg")',
    idMeal: "53063",
  },
  {
    strMeal: "Corned Beef and Cabbage",
    strMealThumb: 'require("../assets/images/meals/52998.jpg")',
    idMeal: "52998",
  },
  {
    strMeal: "Croatian Bean Stew",
    strMealThumb: 'require("../assets/images/meals/53058.jpg")',
    idMeal: "53058",
  },
  {
    strMeal: "Croatian lamb peka",
    strMealThumb: 'require("../assets/images/meals/53056.jpg")',
    idMeal: "53056",
  },
  {
    strMeal: "Egyptian Fatteh",
    strMealThumb: 'require("../assets/images/meals/53031.jpg")',
    idMeal: "53031",
  },
  {
    strMeal: "Gołąbki (cabbage roll)",
    strMealThumb: 'require("../assets/images/meals/53021.jpg")',
    idMeal: "53021",
  },
  {
    strMeal: "Irish stew",
    strMealThumb: 'require("../assets/images/meals/52781.jpg")',
    idMeal: "52781",
  },
  {
    strMeal: "Jamaican Beef Patties",
    strMealThumb: 'require("../assets/images/meals/52938.jpg")',
    idMeal: "52938",
  },
  {
    strMeal: "Ma Po Tofu",
    strMealThumb: 'require("../assets/images/meals/52947.jpg")',
    idMeal: "52947",
  },
  {
    strMeal: "Massaman Beef curry",
    strMealThumb: 'require("../assets/images/meals/52827.jpg")',
    idMeal: "52827",
  },
  {
    strMeal: "Minced Beef Pie",
    strMealThumb: 'require("../assets/images/meals/52876.jpg")',
    idMeal: "52876",
  },
  {
    strMeal: "Montreal Smoked Meat",
    strMealThumb: 'require("../assets/images/meals/52927.jpg")',
    idMeal: "52927",
  },
  {
    strMeal: "Moussaka",
    strMealThumb: 'require("../assets/images/meals/53006.jpg")',
    idMeal: "53006",
  },
  {
    strMeal: "Mulukhiyah",
    strMealThumb: 'require("../assets/images/meals/53029.jpg")',
    idMeal: "53029",
  },
  {
    strMeal: "Oxtail with broad beans",
    strMealThumb: 'require("../assets/images/meals/52943.jpg")',
    idMeal: "52943",
  },
  {
    strMeal: "Paszteciki (Polish Pasties)",
    strMealThumb: 'require("../assets/images/meals/53017.jpg")',
    idMeal: "53017",
  },
  {
    strMeal: "Pate Chinois",
    strMealThumb: 'require("../assets/images/meals/52930.jpg")',
    idMeal: "52930",
  },
  {
    strMeal: "Portuguese prego with green piri-piri",
    strMealThumb: 'require("../assets/images/meals/53042.jpg")',
    idMeal: "53042",
  },
  {
    strMeal: "Red Peas Soup",
    strMealThumb: 'require("../assets/images/meals/52941.jpg")',
    idMeal: "52941",
  },
  {
    strMeal: "Roti john",
    strMealThumb: 'require("../assets/images/meals/53052.jpg")',
    idMeal: "53052",
  },
  {
    strMeal:
      "Soy-Glazed Meatloaves with Wasabi Mashed Potatoes & Roasted Carrots",
    strMealThumb: 'require("../assets/images/meals/52992.jpg")',
    idMeal: "52992",
  },
  {
    strMeal: "Spaghetti Bolognese",
    strMealThumb: 'require("../assets/images/meals/52770.jpg")',
    idMeal: "52770",
  },
  {
    strMeal: "Steak and Kidney Pie",
    strMealThumb: 'require("../assets/images/meals/52881.jpg")',
    idMeal: "52881",
  },
  {
    strMeal: "Steak Diane",
    strMealThumb: 'require("../assets/images/meals/52935.jpg")',
    idMeal: "52935",
  },
  {
    strMeal: "Szechuan Beef",
    strMealThumb: 'require("../assets/images/meals/52950.jpg")',
    idMeal: "52950",
  },
  {
    strMeal: "Traditional Croatian Goulash",
    strMealThumb: 'require("../assets/images/meals/53057.jpg")',
    idMeal: "53057",
  },
  {
    strMeal: "Vegetable Shepherd's Pie",
    strMealThumb: 'require("../assets/images/meals/53000.jpg")',
    idMeal: "53000",
  },
];

export const chickenMeals = [
  {
    strMeal: "15-minute chicken & halloumi burgers",
    strMealThumb: 'require("../assets/images/meals/53085.jpg")',
    idMeal: "53085",
  },
  {
    strMeal: "Ayam Percik",
    strMealThumb: 'require("../assets/images/meals/53050.jpg")',
    idMeal: "53050",
  },
  {
    strMeal: "Brown Stew Chicken",
    strMealThumb: 'require("../assets/images/meals/52940.jpg")',
    idMeal: "52940",
  },
  {
    strMeal: "Chick-Fil-A Sandwich",
    strMealThumb: 'require("../assets/images/meals/53016.jpg")',
    idMeal: "53016",
  },
  {
    strMeal: "Chicken & mushroom Hotpot",
    strMealThumb: 'require("../assets/images/meals/52846.jpg")',
    idMeal: "52846",
  },
  {
    strMeal: "Chicken Alfredo Primavera",
    strMealThumb: 'require("../assets/images/meals/52796.jpg")',
    idMeal: "52796",
  },
  {
    strMeal: "Chicken Basquaise",
    strMealThumb: 'require("../assets/images/meals/52934.jpg")',
    idMeal: "52934",
  },
  {
    strMeal: "Chicken Congee",
    strMealThumb: 'require("../assets/images/meals/52956.jpg")',
    idMeal: "52956",
  },
  {
    strMeal: "Chicken Couscous",
    strMealThumb: 'require("../assets/images/meals/52850.jpg")',
    idMeal: "52850",
  },
  {
    strMeal: "Chicken Enchilada Casserole",
    strMealThumb: 'require("../assets/images/meals/52765.jpg")',
    idMeal: "52765",
  },
  {
    strMeal: "Chicken Fajita Mac and Cheese",
    strMealThumb: 'require("../assets/images/meals/52818.jpg")',
    idMeal: "52818",
  },
  {
    strMeal: "Chicken Ham and Leek Pie",
    strMealThumb: 'require("../assets/images/meals/52875.jpg")',
    idMeal: "52875",
  },
  {
    strMeal: "Chicken Handi",
    strMealThumb: 'require("../assets/images/meals/52795.jpg")',
    idMeal: "52795",
  },
  {
    strMeal: "Chicken Karaage",
    strMealThumb: 'require("../assets/images/meals/52831.jpg")',
    idMeal: "52831",
  },
  {
    strMeal: "Chicken Marengo",
    strMealThumb: 'require("../assets/images/meals/52920.jpg")',
    idMeal: "52920",
  },
  {
    strMeal: "Chicken Parmentier",
    strMealThumb: 'require("../assets/images/meals/52879.jpg")',
    idMeal: "52879",
  },
  {
    strMeal: "Chicken Quinoa Greek Salad",
    strMealThumb: 'require("../assets/images/meals/53011.jpg")',
    idMeal: "53011",
  },
  {
    strMeal: "Coq au vin",
    strMealThumb: 'require("../assets/images/meals/52832.jpg")',
    idMeal: "52832",
  },
  {
    strMeal: "Crock Pot Chicken Baked Tacos",
    strMealThumb: 'require("../assets/images/meals/52830.jpg")',
    idMeal: "52830",
  },
  {
    strMeal: "French Onion Chicken with Roasted Carrots & Mashed Potatoes",
    strMealThumb: 'require("../assets/images/meals/52996.jpg")',
    idMeal: "52996",
  },
  {
    strMeal: "General Tso's Chicken",
    strMealThumb: 'require("../assets/images/meals/52951.jpg")',
    idMeal: "52951",
  },
  {
    strMeal: "Honey Balsamic Chicken with Crispy Broccoli & Potatoes",
    strMealThumb: 'require("../assets/images/meals/52993.jpg")',
    idMeal: "52993",
  },
  {
    strMeal: "Jerk chicken with rice & peas",
    strMealThumb: 'require("../assets/images/meals/52937.jpg")',
    idMeal: "52937",
  },
  {
    strMeal: "Katsu Chicken curry",
    strMealThumb: 'require("../assets/images/meals/52820.jpg")',
    idMeal: "52820",
  },
  {
    strMeal: "Kentucky Fried Chicken",
    strMealThumb: 'require("../assets/images/meals/52813.jpg")',
    idMeal: "52813",
  },
  {
    strMeal: "Kung Pao Chicken",
    strMealThumb: 'require("../assets/images/meals/52945.jpg")',
    idMeal: "52945",
  },
  {
    strMeal: "Nutty Chicken Curry",
    strMealThumb: 'require("../assets/images/meals/52851.jpg")',
    idMeal: "52851",
  },
  {
    strMeal: "Pad See Ew",
    strMealThumb: 'require("../assets/images/meals/52774.jpg")',
    idMeal: "52774",
  },
  {
    strMeal: "Piri-piri chicken and slaw",
    strMealThumb: 'require("../assets/images/meals/53039.jpg")',
    idMeal: "53039",
  },
  {
    strMeal: "Potato Gratin with Chicken",
    strMealThumb: 'require("../assets/images/meals/52780.jpg")',
    idMeal: "52780",
  },
  {
    strMeal: "Rappie Pie",
    strMealThumb: 'require("../assets/images/meals/52933.jpg")',
    idMeal: "52933",
  },
  {
    strMeal: "Rosół (Polish Chicken Soup)",
    strMealThumb: 'require("../assets/images/meals/53020.jpg")',
    idMeal: "53020",
  },
  {
    strMeal: "Shawarma",
    strMealThumb: 'require("../assets/images/meals/53028.jpg")',
    idMeal: "53028",
  },
  {
    strMeal: "Tandoori chicken",
    strMealThumb: 'require("../assets/images/meals/52806.jpg")',
    idMeal: "52806",
  },
  {
    strMeal: "Teriyaki Chicken Casserole",
    strMealThumb: 'require("../assets/images/meals/52772.jpg")',
    idMeal: "52772",
  },
  {
    strMeal: "Thai Green Curry",
    strMealThumb: 'require("../assets/images/meals/52814.jpg")',
    idMeal: "52814",
  },
];

export const dessertMeals = [
  {
    strMeal: "Apam balik",
    strMealThumb: 'require("../assets/images/meals/53049.jpg")',
    idMeal: "53049",
  },
  {
    strMeal: "Apple & Blackberry Crumble",
    strMealThumb: 'require("../assets/images/meals/52893.jpg")',
    idMeal: "52893",
  },
  {
    strMeal: "Apple Frangipan Tart",
    strMealThumb: 'require("../assets/images/meals/52768.jpg")',
    idMeal: "52768",
  },
  {
    strMeal: "Bakewell tart",
    strMealThumb: 'require("../assets/images/meals/52767.jpg")',
    idMeal: "52767",
  },
  {
    strMeal: "Banana Pancakes",
    strMealThumb: 'require("../assets/images/meals/52855.jpg")',
    idMeal: "52855",
  },
  {
    strMeal: "Battenberg Cake",
    strMealThumb: 'require("../assets/images/meals/52894.jpg")',
    idMeal: "52894",
  },
  {
    strMeal: "BeaverTails",
    strMealThumb: 'require("../assets/images/meals/52928.jpg")',
    idMeal: "52928",
  },
  {
    strMeal: "Blackberry Fool",
    strMealThumb: 'require("../assets/images/meals/52891.jpg")',
    idMeal: "52891",
  },
  {
    strMeal: "Bread and Butter Pudding",
    strMealThumb: 'require("../assets/images/meals/52792.jpg")',
    idMeal: "52792",
  },
  {
    strMeal: "Budino Di Ricotta",
    strMealThumb: 'require("../assets/images/meals/52961.jpg")',
    idMeal: "52961",
  },
  {
    strMeal: "Canadian Butter Tarts",
    strMealThumb: 'require("../assets/images/meals/52923.jpg")',
    idMeal: "52923",
  },
  {
    strMeal: "Carrot Cake",
    strMealThumb: 'require("../assets/images/meals/52897.jpg")',
    idMeal: "52897",
  },
  {
    strMeal: "Cashew Ghoriba Biscuits",
    strMealThumb: 'require("../assets/images/meals/52976.jpg")',
    idMeal: "52976",
  },
  {
    strMeal: "Chelsea Buns",
    strMealThumb: 'require("../assets/images/meals/52898.jpg")',
    idMeal: "52898",
  },
  {
    strMeal: "Chinon Apple Tarts",
    strMealThumb: 'require("../assets/images/meals/52910.jpg")',
    idMeal: "52910",
  },
  {
    strMeal: "Choc Chip Pecan Pie",
    strMealThumb: 'require("../assets/images/meals/52856.jpg")',
    idMeal: "52856",
  },
  {
    strMeal: "Chocolate Avocado Mousse",
    strMealThumb: 'require("../assets/images/meals/52853.jpg")',
    idMeal: "52853",
  },
  {
    strMeal: "Chocolate Caramel Crispy",
    strMealThumb: 'require("../assets/images/meals/52966.jpg")',
    idMeal: "52966",
  },
  {
    strMeal: "Chocolate Gateau",
    strMealThumb: 'require("../assets/images/meals/52776.jpg")',
    idMeal: "52776",
  },
  {
    strMeal: "Chocolate Raspberry Brownies",
    strMealThumb: 'require("../assets/images/meals/52860.jpg")',
    idMeal: "52860",
  },
  {
    strMeal: "Chocolate Souffle",
    strMealThumb: 'require("../assets/images/meals/52905.jpg")',
    idMeal: "52905",
  },
  {
    strMeal: "Christmas cake",
    strMealThumb: 'require("../assets/images/meals/52990.jpg")',
    idMeal: "52990",
  },
  {
    strMeal: "Christmas Pudding Flapjack",
    strMealThumb: 'require("../assets/images/meals/52788.jpg")',
    idMeal: "52788",
  },
  {
    strMeal: "Christmas Pudding Trifle",
    strMealThumb: 'require("../assets/images/meals/52989.jpg")',
    idMeal: "52989",
  },
  {
    strMeal: "Classic Christmas pudding",
    strMealThumb: 'require("../assets/images/meals/52988.jpg")',
    idMeal: "52988",
  },
  {
    strMeal: "Dundee cake",
    strMealThumb: 'require("../assets/images/meals/52899.jpg")',
    idMeal: "52899",
  },
  {
    strMeal: "Eccles Cakes",
    strMealThumb: 'require("../assets/images/meals/52888.jpg")',
    idMeal: "52888",
  },
  {
    strMeal: "Eton Mess",
    strMealThumb: 'require("../assets/images/meals/52791.jpg")',
    idMeal: "52791",
  },
  {
    strMeal: "Honey Yogurt Cheesecake",
    strMealThumb: 'require("../assets/images/meals/53007.jpg")',
    idMeal: "53007",
  },
  {
    strMeal: "Hot Chocolate Fudge",
    strMealThumb: 'require("../assets/images/meals/52787.jpg")',
    idMeal: "52787",
  },
  {
    strMeal: "Jam Roly-Poly",
    strMealThumb: 'require("../assets/images/meals/52890.jpg")',
    idMeal: "52890",
  },
  {
    strMeal: "Key Lime Pie",
    strMealThumb: 'require("../assets/images/meals/52859.jpg")',
    idMeal: "52859",
  },
  {
    strMeal: "Krispy Kreme Donut",
    strMealThumb: 'require("../assets/images/meals/53015.jpg")',
    idMeal: "53015",
  },
  {
    strMeal: "Madeira Cake",
    strMealThumb: 'require("../assets/images/meals/52900.jpg")',
    idMeal: "52900",
  },
  {
    strMeal: "Mince Pies",
    strMealThumb: 'require("../assets/images/meals/52991.jpg")',
    idMeal: "52991",
  },
  {
    strMeal: "Nanaimo Bars",
    strMealThumb: 'require("../assets/images/meals/52924.jpg")',
    idMeal: "52924",
  },
  {
    strMeal: "New York cheesecake",
    strMealThumb: 'require("../assets/images/meals/52858.jpg")',
    idMeal: "52858",
  },
  {
    strMeal: "Pancakes",
    strMealThumb: 'require("../assets/images/meals/52854.jpg")',
    idMeal: "52854",
  },
  {
    strMeal: "Parkin Cake",
    strMealThumb: 'require("../assets/images/meals/52902.jpg")',
    idMeal: "52902",
  },
  {
    strMeal: "Peach & Blueberry Grunt",
    strMealThumb: 'require("../assets/images/meals/52862.jpg")',
    idMeal: "52862",
  },
  {
    strMeal: "Peanut Butter Cheesecake",
    strMealThumb: 'require("../assets/images/meals/52861.jpg")',
    idMeal: "52861",
  },
  {
    strMeal: "Peanut Butter Cookies",
    strMealThumb: 'require("../assets/images/meals/52958.jpg")',
    idMeal: "52958",
  },
  {
    strMeal: "Pear Tarte Tatin",
    strMealThumb: 'require("../assets/images/meals/52916.jpg")',
    idMeal: "52916",
  },
  {
    strMeal: "Polskie Naleśniki (Polish Pancakes)",
    strMealThumb: 'require("../assets/images/meals/53022.jpg")',
    idMeal: "53022",
  },
  {
    strMeal: "Portuguese custard tarts",
    strMealThumb: 'require("../assets/images/meals/53046.jpg")',
    idMeal: "53046",
  },
  {
    strMeal: "Pouding chomeur",
    strMealThumb: 'require("../assets/images/meals/52932.jpg")',
    idMeal: "52932",
  },
  {
    strMeal: "Pumpkin Pie",
    strMealThumb: 'require("../assets/images/meals/52857.jpg")',
    idMeal: "52857",
  },
  {
    strMeal: "Rock Cakes",
    strMealThumb: 'require("../assets/images/meals/52901.jpg")',
    idMeal: "52901",
  },
  {
    strMeal: "Rocky Road Fudge",
    strMealThumb: 'require("../assets/images/meals/52786.jpg")',
    idMeal: "52786",
  },
  {
    strMeal: "Rogaliki (Polish Croissant Cookies)",
    strMealThumb: 'require("../assets/images/meals/53024.jpg")',
    idMeal: "53024",
  },
  {
    strMeal: "Salted Caramel Cheescake",
    strMealThumb: 'require("../assets/images/meals/52833.jpg")',
    idMeal: "52833",
  },
  {
    strMeal: "Seri muka kuih",
    strMealThumb: 'require("../assets/images/meals/53054.jpg")',
    idMeal: "53054",
  },
  {
    strMeal: "Spotted Dick",
    strMealThumb: 'require("../assets/images/meals/52886.jpg")',
    idMeal: "52886",
  },
  {
    strMeal: "Sticky Toffee Pudding",
    strMealThumb: 'require("../assets/images/meals/52883.jpg")',
    idMeal: "52883",
  },
  {
    strMeal: "Sticky Toffee Pudding Ultimate",
    strMealThumb: 'require("../assets/images/meals/52793.jpg")',
    idMeal: "52793",
  },
  {
    strMeal: "Strawberries Romanoff",
    strMealThumb: 'require("../assets/images/meals/53082.jpg")',
    idMeal: "53082",
  },
  {
    strMeal: "Strawberry Rhubarb Pie",
    strMealThumb: 'require("../assets/images/meals/53005.jpg")',
    idMeal: "53005",
  },
  {
    strMeal: "Sugar Pie",
    strMealThumb: 'require("../assets/images/meals/52931.jpg")',
    idMeal: "52931",
  },
  {
    strMeal: "Summer Pudding",
    strMealThumb: 'require("../assets/images/meals/52889.jpg")',
    idMeal: "52889",
  },
  {
    strMeal: "Tarte Tatin",
    strMealThumb: 'require("../assets/images/meals/52909.jpg")',
    idMeal: "52909",
  },
  {
    strMeal: "Timbits",
    strMealThumb: 'require("../assets/images/meals/52929.jpg")',
    idMeal: "52929",
  },
  {
    strMeal: "Treacle Tart",
    strMealThumb: 'require("../assets/images/meals/52892.jpg")',
    idMeal: "52892",
  },
  {
    strMeal: "Tunisian Orange Cake",
    strMealThumb: 'require("../assets/images/meals/52970.jpg")',
    idMeal: "52970",
  },
  {
    strMeal: "Walnut Roll Gužvara",
    strMealThumb: 'require("../assets/images/meals/53062.jpg")',
    idMeal: "53062",
  },
  {
    strMeal: "White chocolate creme brulee",
    strMealThumb: 'require("../assets/images/meals/52917.jpg")',
    idMeal: "52917",
  },
];

export const lambMeals = [
  {
    strMeal: "Kapsalon",
    strMealThumb: 'require("../assets/images/meals/52769.jpg")',
    idMeal: "52769",
  },
  {
    strMeal: "Keleya Zaara",
    strMealThumb: 'require("../assets/images/meals/52974.jpg")',
    idMeal: "52974",
  },
  {
    strMeal: "Lamb and Lemon Souvlaki",
    strMealThumb: 'require("../assets/images/meals/53009.jpg")',
    idMeal: "53009",
  },
  {
    strMeal: "Lamb and Potato pie",
    strMealThumb: 'require("../assets/images/meals/52877.jpg")',
    idMeal: "52877",
  },
  {
    strMeal: "Lamb Biryani",
    strMealThumb: 'require("../assets/images/meals/52805.jpg")',
    idMeal: "52805",
  },
  {
    strMeal: "Lamb Pilaf (Plov)",
    strMealThumb: 'require("../assets/images/meals/53083.jpg")',
    idMeal: "53083",
  },
  {
    strMeal: "Lamb Rogan josh",
    strMealThumb: 'require("../assets/images/meals/52808.jpg")',
    idMeal: "52808",
  },
  {
    strMeal: "Lamb Tagine",
    strMealThumb: 'require("../assets/images/meals/52843.jpg")',
    idMeal: "52843",
  },
  {
    strMeal: "Lamb tomato and sweet spices",
    strMealThumb: 'require("../assets/images/meals/52782.jpg")',
    idMeal: "52782",
  },
  {
    strMeal: "Lamb Tzatziki Burgers",
    strMealThumb: 'require("../assets/images/meals/53010.jpg")',
    idMeal: "53010",
  },
  {
    strMeal: "Lancashire hotpot",
    strMealThumb: 'require("../assets/images/meals/52884.jpg")',
    idMeal: "52884",
  },
  {
    strMeal: "McSinghs Scotch pie",
    strMealThumb: 'require("../assets/images/meals/52880.jpg")',
    idMeal: "52880",
  },
  {
    strMeal: "Rigatoni with fennel sausage sauce",
    strMealThumb: 'require("../assets/images/meals/52783.jpg")',
    idMeal: "52783",
  },
  {
    strMeal: "Stuffed Lamb Tomatoes",
    strMealThumb: 'require("../assets/images/meals/53008.jpg")',
    idMeal: "53008",
  },
  {
    strMeal: "Tunisian Lamb Soup",
    strMealThumb: 'require("../assets/images/meals/52972.jpg")',
    idMeal: "52972",
  },
];

export const miscellaneousMeals = [
  {
    strMeal: "Bean & Sausage Hotpot",
    strMealThumb: 'require("../assets/images/meals/52848.jpg")',
    idMeal: "52848",
  },
  {
    strMeal: "Callaloo Jamaican Style",
    strMealThumb: 'require("../assets/images/meals/52939.jpg")',
    idMeal: "52939",
  },
  {
    strMeal: "Chakchouka ",
    strMealThumb: 'require("../assets/images/meals/52969.jpg")',
    idMeal: "52969",
  },
  {
    strMeal: "Duck Confit",
    strMealThumb: 'require("../assets/images/meals/52907.jpg")',
    idMeal: "52907",
  },
  {
    strMeal: "French Lentils With Garlic and Thyme",
    strMealThumb: 'require("../assets/images/meals/52815.jpg")',
    idMeal: "52815",
  },
  {
    strMeal: "French Omelette",
    strMealThumb: 'require("../assets/images/meals/52915.jpg")',
    idMeal: "52915",
  },
  {
    strMeal: "Osso Buco alla Milanese",
    strMealThumb: 'require("../assets/images/meals/52810.jpg")',
    idMeal: "52810",
  },
  {
    strMeal: "Pizza Express Margherita",
    strMealThumb: 'require("../assets/images/meals/53014.jpg")',
    idMeal: "53014",
  },
  {
    strMeal: "Poutine",
    strMealThumb: 'require("../assets/images/meals/52804.jpg")',
    idMeal: "52804",
  },
  {
    strMeal: "Three-cheese souffles",
    strMealThumb: 'require("../assets/images/meals/52912.jpg")',
    idMeal: "52912",
  },
  {
    strMeal: "Turkey Meatloaf",
    strMealThumb: 'require("../assets/images/meals/52845.jpg")',
    idMeal: "52845",
  },
];

export const pastaMeals = [
  {
    strMeal: "Chilli prawn linguine",
    strMealThumb: 'require("../assets/images/meals/52839.jpg")',
    idMeal: "52839",
  },
  {
    strMeal: "Fettuccine Alfredo",
    strMealThumb: 'require("../assets/images/meals/53064.jpg")',
    idMeal: "53064",
  },
  {
    strMeal: "Fettucine alfredo",
    strMealThumb: 'require("../assets/images/meals/52835.jpg")',
    idMeal: "52835",
  },
  {
    strMeal: "Grilled Mac and Cheese Sandwich",
    strMealThumb: 'require("../assets/images/meals/52829.jpg")',
    idMeal: "52829",
  },
  {
    strMeal: "Lasagna Sandwiches",
    strMealThumb: 'require("../assets/images/meals/52987.jpg")',
    idMeal: "52987",
  },
  {
    strMeal: "Lasagne",
    strMealThumb: 'require("../assets/images/meals/52844.jpg")',
    idMeal: "52844",
  },
  {
    strMeal: "Pilchard puttanesca",
    strMealThumb: 'require("../assets/images/meals/52837.jpg")',
    idMeal: "52837",
  },
  {
    strMeal: "Spaghetti alla Carbonara",
    strMealThumb: 'require("../assets/images/meals/52982.jpg")',
    idMeal: "52982",
  },
  {
    strMeal: "Venetian Duck Ragu",
    strMealThumb: 'require("../assets/images/meals/52838.jpg")',
    idMeal: "52838",
  },
];

export const porkMeals = [
  {
    strMeal: " Bubble & Squeak",
    strMealThumb: 'require("../assets/images/meals/52885.jpg")',
    idMeal: "52885",
  },
  {
    strMeal: "BBQ Pork Sloppy Joes",
    strMealThumb: 'require("../assets/images/meals/52995.jpg")',
    idMeal: "52995",
  },
  {
    strMeal: "Bigos (Hunters Stew)",
    strMealThumb: 'require("../assets/images/meals/53018.jpg")',
    idMeal: "53018",
  },
  {
    strMeal: "Boxty Breakfast",
    strMealThumb: 'require("../assets/images/meals/53036.jpg")',
    idMeal: "53036",
  },
  {
    strMeal: "Coddled pork with cider",
    strMealThumb: 'require("../assets/images/meals/53037.jpg")',
    idMeal: "53037",
  },
  {
    strMeal: "Crispy Sausages and Greens",
    strMealThumb: 'require("../assets/images/meals/52999.jpg")',
    idMeal: "52999",
  },
  {
    strMeal: "Ham hock colcannon",
    strMealThumb: 'require("../assets/images/meals/53035.jpg")',
    idMeal: "53035",
  },
  {
    strMeal: "Hot and Sour Soup",
    strMealThumb: 'require("../assets/images/meals/52954.jpg")',
    idMeal: "52954",
  },
  {
    strMeal: "Japanese Katsudon",
    strMealThumb: 'require("../assets/images/meals/53034.jpg")',
    idMeal: "53034",
  },
  {
    strMeal: "Pork Cassoulet",
    strMealThumb: 'require("../assets/images/meals/52847.jpg")',
    idMeal: "52847",
  },
  {
    strMeal: "Portuguese barbecued pork (Febras assadas)",
    strMealThumb: 'require("../assets/images/meals/53044.jpg")',
    idMeal: "53044",
  },
  {
    strMeal: "Skillet Apple Pork Chops with Roasted Sweet Potatoes & Zucchini",
    strMealThumb: 'require("../assets/images/meals/52994.jpg")',
    idMeal: "52994",
  },
  {
    strMeal: "Stamppot",
    strMealThumb: 'require("../assets/images/meals/52980.jpg")',
    idMeal: "52980",
  },
  {
    strMeal: "Sweet and Sour Pork",
    strMealThumb: 'require("../assets/images/meals/52949.jpg")',
    idMeal: "52949",
  },
  {
    strMeal: "Toad In The Hole",
    strMealThumb: 'require("../assets/images/meals/52822.jpg")',
    idMeal: "52822",
  },
  {
    strMeal: "Tonkatsu pork",
    strMealThumb: 'require("../assets/images/meals/53032.jpg")',
    idMeal: "53032",
  },
  {
    strMeal: "Tourtiere",
    strMealThumb: 'require("../assets/images/meals/52926.jpg")',
    idMeal: "52926",
  },
  {
    strMeal: "Vietnamese Grilled Pork (bun-thit-nuong)",
    strMealThumb: 'require("../assets/images/meals/52828.jpg")',
    idMeal: "52828",
  },
  {
    strMeal: "Wontons",
    strMealThumb: 'require("../assets/images/meals/52948.jpg")',
    idMeal: "52948",
  },
];

export const seafoodMeals = [
  {
    strMeal: "Baked salmon with fennel & tomatoes",
    strMealThumb: 'require("../assets/images/meals/52959.jpg")',
    idMeal: "52959",
  },
  {
    strMeal: "Cajun spiced fish tacos",
    strMealThumb: 'require("../assets/images/meals/52819.jpg")',
    idMeal: "52819",
  },
  {
    strMeal: "Escovitch Fish",
    strMealThumb: 'require("../assets/images/meals/52944.jpg")',
    idMeal: "52944",
  },
  {
    strMeal: "Fish fofos",
    strMealThumb: 'require("../assets/images/meals/53043.jpg")',
    idMeal: "53043",
  },
  {
    strMeal: "Fish pie",
    strMealThumb: 'require("../assets/images/meals/52802.jpg")',
    idMeal: "52802",
  },
  {
    strMeal: "Fish Soup (Ukha)",
    strMealThumb: 'require("../assets/images/meals/53079.jpg")',
    idMeal: "53079",
  },
  {
    strMeal: "Fish Stew with Rouille",
    strMealThumb: 'require("../assets/images/meals/52918.jpg")',
    idMeal: "52918",
  },
  {
    strMeal: "Garides Saganaki",
    strMealThumb: 'require("../assets/images/meals/52764.jpg")',
    idMeal: "52764",
  },
  {
    strMeal: "Grilled Portuguese sardines",
    strMealThumb: 'require("../assets/images/meals/53041.jpg")',
    idMeal: "53041",
  },
  {
    strMeal: "Honey Teriyaki Salmon",
    strMealThumb: 'require("../assets/images/meals/52773.jpg")',
    idMeal: "52773",
  },
  {
    strMeal: "Kedgeree",
    strMealThumb: 'require("../assets/images/meals/52887.jpg")',
    idMeal: "52887",
  },
  {
    strMeal: "Kung Po Prawns",
    strMealThumb: 'require("../assets/images/meals/52946.jpg")',
    idMeal: "52946",
  },
  {
    strMeal: "Laksa King Prawn Noodles",
    strMealThumb: 'require("../assets/images/meals/52821.jpg")',
    idMeal: "52821",
  },
  {
    strMeal: "Mediterranean Pasta Salad",
    strMealThumb: 'require("../assets/images/meals/52777.jpg")',
    idMeal: "52777",
  },
  {
    strMeal: "Mee goreng mamak",
    strMealThumb: 'require("../assets/images/meals/53048.jpg")',
    idMeal: "53048",
  },
  {
    strMeal: "Nasi lemak",
    strMealThumb: 'require("../assets/images/meals/53051.jpg")',
    idMeal: "53051",
  },
  {
    strMeal: "Portuguese fish stew (Caldeirada de peixe)",
    strMealThumb: 'require("../assets/images/meals/53045.jpg")',
    idMeal: "53045",
  },
  {
    strMeal: "Recheado Masala Fish",
    strMealThumb: 'require("../assets/images/meals/52809.jpg")',
    idMeal: "52809",
  },
  {
    strMeal: "Salmon Avocado Salad",
    strMealThumb: 'require("../assets/images/meals/52960.jpg")',
    idMeal: "52960",
  },
  {
    strMeal: "Salmon Prawn Risotto",
    strMealThumb: 'require("../assets/images/meals/52823.jpg")',
    idMeal: "52823",
  },
  {
    strMeal: "Saltfish and Ackee",
    strMealThumb: 'require("../assets/images/meals/52936.jpg")',
    idMeal: "52936",
  },
  {
    strMeal: "Seafood fideuà",
    strMealThumb: 'require("../assets/images/meals/52836.jpg")',
    idMeal: "52836",
  },
  {
    strMeal: "Shrimp Chow Fun",
    strMealThumb: 'require("../assets/images/meals/52953.jpg")',
    idMeal: "52953",
  },
  {
    strMeal: "Sledz w Oleju (Polish Herrings)",
    strMealThumb: 'require("../assets/images/meals/53023.jpg")',
    idMeal: "53023",
  },
  {
    strMeal: "Spring onion and prawn empanadas",
    strMealThumb: 'require("../assets/images/meals/53040.jpg")',
    idMeal: "53040",
  },
  {
    strMeal: "Sushi",
    strMealThumb: 'require("../assets/images/meals/53065.jpg")',
    idMeal: "53065",
  },
  {
    strMeal: "Three Fish Pie",
    strMealThumb: 'require("../assets/images/meals/52882.jpg")',
    idMeal: "52882",
  },
  {
    strMeal: "Tuna and Egg Briks",
    strMealThumb: 'require("../assets/images/meals/52975.jpg")',
    idMeal: "52975",
  },
  {
    strMeal: "Tuna Nicoise",
    strMealThumb: 'require("../assets/images/meals/52852.jpg")',
    idMeal: "52852",
  },
];

export const sideMeals = [
  {
    strMeal: "Blini Pancakes",
    strMealThumb: 'require("../assets/images/meals/53080.jpg")',
    idMeal: "53080",
  },
  {
    strMeal: "Boulangère Potatoes",
    strMealThumb: 'require("../assets/images/meals/52914.jpg")',
    idMeal: "52914",
  },
  {
    strMeal: "Brie wrapped in prosciutto & brioche",
    strMealThumb: 'require("../assets/images/meals/52913.jpg")',
    idMeal: "52913",
  },
  {
    strMeal: "Burek",
    strMealThumb: 'require("../assets/images/meals/53060.jpg")',
    idMeal: "53060",
  },
  {
    strMeal: "Corba",
    strMealThumb: 'require("../assets/images/meals/52977.jpg")',
    idMeal: "52977",
  },
  {
    strMeal: "Fennel Dauphinoise",
    strMealThumb: 'require("../assets/images/meals/52919.jpg")',
    idMeal: "52919",
  },
  {
    strMeal: "Feteer Meshaltet",
    strMealThumb: 'require("../assets/images/meals/53030.jpg")',
    idMeal: "53030",
  },
  {
    strMeal: "French Onion Soup",
    strMealThumb: 'require("../assets/images/meals/52903.jpg")',
    idMeal: "52903",
  },
  {
    strMeal: "Fresh sardines",
    strMealThumb: 'require("../assets/images/meals/53061.jpg")',
    idMeal: "53061",
  },
  {
    strMeal: "Japanese gohan rice",
    strMealThumb: 'require("../assets/images/meals/53033.jpg")',
    idMeal: "53033",
  },
  {
    strMeal: "Kumpir",
    strMealThumb: 'require("../assets/images/meals/52978.jpg")',
    idMeal: "52978",
  },
  {
    strMeal: "Mushroom soup with buckwheat",
    strMealThumb: 'require("../assets/images/meals/53059.jpg")',
    idMeal: "53059",
  },
  {
    strMeal: "Mustard champ",
    strMealThumb: 'require("../assets/images/meals/53038.jpg")',
    idMeal: "53038",
  },
  {
    strMeal: "Pierogi (Polish Dumplings)",
    strMealThumb: 'require("../assets/images/meals/53019.jpg")',
    idMeal: "53019",
  },
  {
    strMeal: "Prawn & Fennel Bisque",
    strMealThumb: 'require("../assets/images/meals/52922.jpg")',
    idMeal: "52922",
  },
  {
    strMeal: "Snert (Dutch Split Pea Soup)",
    strMealThumb: 'require("../assets/images/meals/52981.jpg")',
    idMeal: "52981",
  },
  {
    strMeal: "Split Pea Soup",
    strMealThumb: 'require("../assets/images/meals/52925.jpg")',
    idMeal: "52925",
  },
];

export const starterMeals = [
  {
    strMeal: "Broccoli & Stilton soup",
    strMealThumb: 'require("../assets/images/meals/52842.jpg")',
    idMeal: "52842",
  },
  {
    strMeal: "Clam chowder",
    strMealThumb: 'require("../assets/images/meals/52840.jpg")',
    idMeal: "52840",
  },
  {
    strMeal: "Cream Cheese Tart",
    strMealThumb: 'require("../assets/images/meals/52779.jpg")',
    idMeal: "52779",
  },
  {
    strMeal: "Creamy Tomato Soup",
    strMealThumb: 'require("../assets/images/meals/52841.jpg")',
    idMeal: "52841",
  },
];

export const veganMeals = [
  {
    strMeal: "Roast fennel and aubergine paella",
    strMealThumb: 'require("../assets/images/meals/52942.jpg")',
    idMeal: "52942",
  },
  {
    strMeal: "Vegan Chocolate Cake",
    strMealThumb: 'require("../assets/images/meals/52794.jpg")',
    idMeal: "52794",
  },
  {
    strMeal: "Vegan Lasagna",
    strMealThumb: 'require("../assets/images/meals/52775.jpg")',
    idMeal: "52775",
  },
];

export const vegetarianMeals = [
  {
    strMeal: "Baingan Bharta",
    strMealThumb: 'require("../assets/images/meals/52807.jpg")',
    idMeal: "52807",
  },
  {
    strMeal: "Beetroot Soup (Borscht)",
    strMealThumb: 'require("../assets/images/meals/53078.jpg")',
    idMeal: "53078",
  },
  {
    strMeal: "Cabbage Soup (Shchi)",
    strMealThumb: 'require("../assets/images/meals/53077.jpg")',
    idMeal: "53077",
  },
  {
    strMeal: "Chickpea Fajitas",
    strMealThumb: 'require("../assets/images/meals/52870.jpg")',
    idMeal: "52870",
  },
  {
    strMeal: "Crispy Eggplant",
    strMealThumb: 'require("../assets/images/meals/53072.jpg")',
    idMeal: "53072",
  },
  {
    strMeal: "Dal fry",
    strMealThumb: 'require("../assets/images/meals/52785.jpg")',
    idMeal: "52785",
  },
  {
    strMeal: "Egg Drop Soup",
    strMealThumb: 'require("../assets/images/meals/52955.jpg")',
    idMeal: "52955",
  },
  {
    strMeal: "Eggplant Adobo",
    strMealThumb: 'require("../assets/images/meals/53073.jpg")',
    idMeal: "53073",
  },
  {
    strMeal: "Flamiche",
    strMealThumb: 'require("../assets/images/meals/52906.jpg")',
    idMeal: "52906",
  },
  {
    strMeal: "Ful Medames",
    strMealThumb: 'require("../assets/images/meals/53025.jpg")',
    idMeal: "53025",
  },
  {
    strMeal: "Gigantes Plaki",
    strMealThumb: 'require("../assets/images/meals/53012.jpg")',
    idMeal: "53012",
  },
  {
    strMeal: "Grilled eggplant with coconut milk",
    strMealThumb: 'require("../assets/images/meals/53074.jpg")',
    idMeal: "53074",
  },
  {
    strMeal: "Kafteji",
    strMealThumb: 'require("../assets/images/meals/52971.jpg")',
    idMeal: "52971",
  },
  {
    strMeal: "Kidney Bean Curry",
    strMealThumb: 'require("../assets/images/meals/52868.jpg")',
    idMeal: "52868",
  },
  {
    strMeal: "Koshari",
    strMealThumb: 'require("../assets/images/meals/53027.jpg")',
    idMeal: "53027",
  },
  {
    strMeal: "Leblebi Soup",
    strMealThumb: 'require("../assets/images/meals/52973.jpg")',
    idMeal: "52973",
  },
  {
    strMeal: "Matar Paneer",
    strMealThumb: 'require("../assets/images/meals/52865.jpg")',
    idMeal: "52865",
  },
  {
    strMeal: "Moroccan Carrot Soup",
    strMealThumb: 'require("../assets/images/meals/53047.jpg")',
    idMeal: "53047",
  },
  {
    strMeal: "Mushroom & Chestnut Rotolo",
    strMealThumb: 'require("../assets/images/meals/52864.jpg")',
    idMeal: "52864",
  },
  {
    strMeal: "Potato Salad (Olivier Salad)",
    strMealThumb: 'require("../assets/images/meals/53081.jpg")',
    idMeal: "53081",
  },
  {
    strMeal: "Provençal Omelette Cake",
    strMealThumb: 'require("../assets/images/meals/52921.jpg")',
    idMeal: "52921",
  },
  {
    strMeal: "Ratatouille",
    strMealThumb: 'require("../assets/images/meals/52908.jpg")',
    idMeal: "52908",
  },
  {
    strMeal: "Ribollita",
    strMealThumb: 'require("../assets/images/meals/52811.jpg")',
    idMeal: "52811",
  },
  {
    strMeal: "Roasted Eggplant With Tahini, Pine Nuts, and Lentils",
    strMealThumb: 'require("../assets/images/meals/52816.jpg")',
    idMeal: "52816",
  },
  {
    strMeal: "Shakshuka",
    strMealThumb: 'require("../assets/images/meals/52963.jpg")',
    idMeal: "52963",
  },
  {
    strMeal: "Smoky Lentil Chili with Squash",
    strMealThumb: 'require("../assets/images/meals/52784.jpg")',
    idMeal: "52784",
  },
  {
    strMeal: "Spanish Tortilla",
    strMealThumb: 'require("../assets/images/meals/52872.jpg")',
    idMeal: "52872",
  },
  {
    strMeal: "Spicy Arrabiata Penne",
    strMealThumb: 'require("../assets/images/meals/52771.jpg")',
    idMeal: "52771",
  },
  {
    strMeal: "Spicy North African Potato Salad",
    strMealThumb: 'require("../assets/images/meals/52797.jpg")',
    idMeal: "52797",
  },
  {
    strMeal: "Spinach & Ricotta Cannelloni",
    strMealThumb: 'require("../assets/images/meals/52849.jpg")',
    idMeal: "52849",
  },
  {
    strMeal: "Squash linguine",
    strMealThumb: 'require("../assets/images/meals/52866.jpg")',
    idMeal: "52866",
  },
  {
    strMeal: "Stovetop Eggplant With Harissa, Chickpeas, and Cumin Yogurt",
    strMealThumb: 'require("../assets/images/meals/52817.jpg")',
    idMeal: "52817",
  },
  {
    strMeal: "Stuffed Bell Peppers with Quinoa and Black Beans",
    strMealThumb: 'require("../assets/images/meals/53067.jpg")',
    idMeal: "53067",
  },
  {
    strMeal: "Summer Pistou",
    strMealThumb: 'require("../assets/images/meals/52911.jpg")',
    idMeal: "52911",
  },
  {
    strMeal: "Tahini Lentils",
    strMealThumb: 'require("../assets/images/meals/52869.jpg")',
    idMeal: "52869",
  },
  {
    strMeal: "Tamiya",
    strMealThumb: 'require("../assets/images/meals/53026.jpg")',
    idMeal: "53026",
  },
  {
    strMeal: "Tortang Talong",
    strMealThumb: 'require("../assets/images/meals/53075.jpg")',
    idMeal: "53075",
  },
  {
    strMeal: "Vegetarian Casserole",
    strMealThumb: 'require("../assets/images/meals/52863.jpg")',
    idMeal: "52863",
  },
  {
    strMeal: "Vegetarian Chilli",
    strMealThumb: 'require("../assets/images/meals/52867.jpg")',
    idMeal: "52867",
  },
  {
    strMeal: "Yaki Udon",
    strMealThumb: 'require("../assets/images/meals/52871.jpg")',
    idMeal: "52871",
  },
];

export const breakfastMeals = [
  {
    strMeal: "Bread omelette",
    strMealThumb: 'require("../assets/images/meals/53076.jpg")',
    idMeal: "53076",
  },
  {
    strMeal: "Breakfast Potatoes",
    strMealThumb: 'require("../assets/images/meals/52965.jpg")',
    idMeal: "52965",
  },
  {
    strMeal: "English Breakfast",
    strMealThumb: 'require("../assets/images/meals/52895.jpg")',
    idMeal: "52895",
  },
  {
    strMeal: "Fruit and Cream Cheese Breakfast Pastries",
    strMealThumb: 'require("../assets/images/meals/52957.jpg")',
    idMeal: "52957",
  },
  {
    strMeal: "Full English Breakfast",
    strMealThumb: 'require("../assets/images/meals/52896.jpg")',
    idMeal: "52896",
  },
  {
    strMeal: "Home-made Mandazi",
    strMealThumb: 'require("../assets/images/meals/52967.jpg")',
    idMeal: "52967",
  },
  {
    strMeal: "Salmon Eggs Eggs Benedict",
    strMealThumb: 'require("../assets/images/meals/52962.jpg")',
    idMeal: "52962",
  },
  {
    strMeal: "Smoked Haddock Kedgeree",
    strMealThumb: 'require("../assets/images/meals/52964.jpg")',
    idMeal: "52964",
  },
];

export const goatMeals = [
  {
    strMeal: "Mbuzi Choma (Roasted Goat)",
    strMealThumb: 'require("../assets/images/meals/52968.jpg")',
    idMeal: "52968",
  },
];

export const meals = [
  {
    strMeal: "Beef and Mustard Pie",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52874.jpg")',
    idMeal: "52874",
  },
  {
    strMeal: "Beef Asado",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53071.jpg")',
    idMeal: "53071",
  },
  {
    strMeal: "Beef Banh Mi Bowls with Sriracha Mayo, Carrot & Pickled Cucumber",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52997.jpg")',
    idMeal: "52997",
  },
  {
    strMeal: "Beef Bourguignon",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52904.jpg")',
    idMeal: "52904",
  },
  {
    strMeal: "Beef Brisket Pot Roast",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52812.jpg")',
    idMeal: "52812",
  },
  {
    strMeal: "Beef Caldereta",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53070.jpg")',
    idMeal: "53070",
  },
  {
    strMeal: "Beef Dumpling Stew",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52873.jpg")',
    idMeal: "52873",
  },
  {
    strMeal: "Beef Lo Mein",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52952.jpg")',
    idMeal: "52952",
  },
  {
    strMeal: "Beef Mechado",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53068.jpg")',
    idMeal: "53068",
  },
  {
    strMeal: "Beef Rendang",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53053.jpg")',
    idMeal: "53053",
  },
  {
    strMeal: "Beef stroganoff",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52834.jpg")',
    idMeal: "52834",
  },
  {
    strMeal: "Beef Sunday Roast",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52824.jpg")',
    idMeal: "52824",
  },
  {
    strMeal: "Beef Wellington",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52803.jpg")',
    idMeal: "52803",
  },
  {
    strMeal: "Big Mac",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53013.jpg")',
    idMeal: "53013",
  },
  {
    strMeal: "Bistek",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53069.jpg")',
    idMeal: "53069",
  },
  {
    strMeal: "Bitterballen (Dutch meatballs)",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52979.jpg")',
    idMeal: "52979",
  },
  {
    strMeal: "Braised Beef Chilli",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52826.jpg")',
    idMeal: "52826",
  },
  {
    strMeal: "Cevapi Sausages",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53055.jpg")',
    idMeal: "53055",
  },
  {
    strMeal: "Chivito uruguayo",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53063.jpg")',
    idMeal: "53063",
  },
  {
    strMeal: "Corned Beef and Cabbage",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52998.jpg")',
    idMeal: "52998",
  },
  {
    strMeal: "Croatian Bean Stew",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53058.jpg")',
    idMeal: "53058",
  },
  {
    strMeal: "Croatian lamb peka",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53056.jpg")',
    idMeal: "53056",
  },
  {
    strMeal: "Egyptian Fatteh",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53031.jpg")',
    idMeal: "53031",
  },
  {
    strMeal: "Gołąbki (cabbage roll)",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53021.jpg")',
    idMeal: "53021",
  },
  {
    strMeal: "Irish stew",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52781.jpg")',
    idMeal: "52781",
  },
  {
    strMeal: "Jamaican Beef Patties",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52938.jpg")',
    idMeal: "52938",
  },
  {
    strMeal: "Ma Po Tofu",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52947.jpg")',
    idMeal: "52947",
  },
  {
    strMeal: "Massaman Beef curry",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52827.jpg")',
    idMeal: "52827",
  },
  {
    strMeal: "Minced Beef Pie",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52876.jpg")',
    idMeal: "52876",
  },
  {
    strMeal: "Montreal Smoked Meat",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52927.jpg")',
    idMeal: "52927",
  },
  {
    strMeal: "Moussaka",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53006.jpg")',
    idMeal: "53006",
  },
  {
    strMeal: "Mulukhiyah",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53029.jpg")',
    idMeal: "53029",
  },
  {
    strMeal: "Oxtail with broad beans",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52943.jpg")',
    idMeal: "52943",
  },
  {
    strMeal: "Paszteciki (Polish Pasties)",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53017.jpg")',
    idMeal: "53017",
  },
  {
    strMeal: "Pate Chinois",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52930.jpg")',
    idMeal: "52930",
  },
  {
    strMeal: "Portuguese prego with green piri-piri",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53042.jpg")',
    idMeal: "53042",
  },
  {
    strMeal: "Red Peas Soup",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52941.jpg")',
    idMeal: "52941",
  },
  {
    strMeal: "Roti john",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53052.jpg")',
    idMeal: "53052",
  },
  {
    strMeal:
      "Soy-Glazed Meatloaves with Wasabi Mashed Potatoes & Roasted Carrots",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52992.jpg")',
    idMeal: "52992",
  },
  {
    strMeal: "Spaghetti Bolognese",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52770.jpg")',
    idMeal: "52770",
  },
  {
    strMeal: "Steak and Kidney Pie",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52881.jpg")',
    idMeal: "52881",
  },
  {
    strMeal: "Steak Diane",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52935.jpg")',
    idMeal: "52935",
  },
  {
    strMeal: "Szechuan Beef",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/52950.jpg")',
    idMeal: "52950",
  },
  {
    strMeal: "Traditional Croatian Goulash",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53057.jpg")',
    idMeal: "53057",
  },
  {
    strMeal: "Vegetable Shepherd's Pie",
    category: "Beef",
    strMealThumb: 'require("../assets/images/meals/53000.jpg")',
    idMeal: "53000",
  },
  {
    strMeal: "15-minute chicken & halloumi burgers",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/53085.jpg")',
    idMeal: "53085",
  },
  {
    strMeal: "Ayam Percik",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/53050.jpg")',
    idMeal: "53050",
  },
  {
    strMeal: "Brown Stew Chicken",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52940.jpg")',
    idMeal: "52940",
  },
  {
    strMeal: "Chick-Fil-A Sandwich",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/53016.jpg")',
    idMeal: "53016",
  },
  {
    strMeal: "Chicken & mushroom Hotpot",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52846.jpg")',
    idMeal: "52846",
  },
  {
    strMeal: "Chicken Alfredo Primavera",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52796.jpg")',
    idMeal: "52796",
  },
  {
    strMeal: "Chicken Basquaise",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52934.jpg")',
    idMeal: "52934",
  },
  {
    strMeal: "Chicken Congee",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52956.jpg")',
    idMeal: "52956",
  },
  {
    strMeal: "Chicken Couscous",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52850.jpg")',
    idMeal: "52850",
  },
  {
    strMeal: "Chicken Enchilada Casserole",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52765.jpg")',
    idMeal: "52765",
  },
  {
    strMeal: "Chicken Fajita Mac and Cheese",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52818.jpg")',
    idMeal: "52818",
  },
  {
    strMeal: "Chicken Ham and Leek Pie",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52875.jpg")',
    idMeal: "52875",
  },
  {
    strMeal: "Chicken Handi",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52795.jpg")',
    idMeal: "52795",
  },
  {
    strMeal: "Chicken Karaage",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52831.jpg")',
    idMeal: "52831",
  },
  {
    strMeal: "Chicken Marengo",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52920.jpg")',
    idMeal: "52920",
  },
  {
    strMeal: "Chicken Parmentier",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52879.jpg")',
    idMeal: "52879",
  },
  {
    strMeal: "Chicken Quinoa Greek Salad",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/53011.jpg")',
    idMeal: "53011",
  },
  {
    strMeal: "Coq au vin",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52832.jpg")',
    idMeal: "52832",
  },
  {
    strMeal: "Crock Pot Chicken Baked Tacos",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52830.jpg")',
    idMeal: "52830",
  },
  {
    strMeal: "French Onion Chicken with Roasted Carrots & Mashed Potatoes",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52996.jpg")',
    idMeal: "52996",
  },
  {
    strMeal: "General Tso's Chicken",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52951.jpg")',
    idMeal: "52951",
  },
  {
    strMeal: "Honey Balsamic Chicken with Crispy Broccoli & Potatoes",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52993.jpg")',
    idMeal: "52993",
  },
  {
    strMeal: "Jerk chicken with rice & peas",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52937.jpg")',
    idMeal: "52937",
  },
  {
    strMeal: "Katsu Chicken curry",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52820.jpg")',
    idMeal: "52820",
  },
  {
    strMeal: "Kentucky Fried Chicken",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52813.jpg")',
    idMeal: "52813",
  },
  {
    strMeal: "Kung Pao Chicken",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52945.jpg")',
    idMeal: "52945",
  },
  {
    strMeal: "Nutty Chicken Curry",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52851.jpg")',
    idMeal: "52851",
  },
  {
    strMeal: "Pad See Ew",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52774.jpg")',
    idMeal: "52774",
  },
  {
    strMeal: "Piri-piri chicken and slaw",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/53039.jpg")',
    idMeal: "53039",
  },
  {
    strMeal: "Potato Gratin with Chicken",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52780.jpg")',
    idMeal: "52780",
  },
  {
    strMeal: "Rappie Pie",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52933.jpg")',
    idMeal: "52933",
  },
  {
    strMeal: "Rosół (Polish Chicken Soup)",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/53020.jpg")',
    idMeal: "53020",
  },
  {
    strMeal: "Shawarma",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/53028.jpg")',
    idMeal: "53028",
  },
  {
    strMeal: "Tandoori chicken",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52806.jpg")',
    idMeal: "52806",
  },
  {
    strMeal: "Teriyaki Chicken Casserole",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52772.jpg")',
    idMeal: "52772",
  },
  {
    strMeal: "Thai Green Curry",
    category: "Chicken",
    strMealThumb: 'require("../assets/images/meals/52814.jpg")',
    idMeal: "52814",
  },

  {
    strMeal: "Apam balik",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/53049.jpg")',
    idMeal: "53049",
  },
  {
    strMeal: "Apple & Blackberry Crumble",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52893.jpg")',
    idMeal: "52893",
  },
  {
    strMeal: "Apple Frangipan Tart",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52768.jpg")',
    idMeal: "52768",
  },
  {
    strMeal: "Bakewell tart",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52767.jpg")',
    idMeal: "52767",
  },
  {
    strMeal: "Banana Pancakes",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52855.jpg")',
    idMeal: "52855",
  },
  {
    strMeal: "Battenberg Cake",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52894.jpg")',
    idMeal: "52894",
  },
  {
    strMeal: "BeaverTails",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52928.jpg")',
    idMeal: "52928",
  },
  {
    strMeal: "Blackberry Fool",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52891.jpg")',
    idMeal: "52891",
  },
  {
    strMeal: "Bread and Butter Pudding",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52792.jpg")',
    idMeal: "52792",
  },
  {
    strMeal: "Budino Di Ricotta",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52961.jpg")',
    idMeal: "52961",
  },
  {
    strMeal: "Canadian Butter Tarts",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52923.jpg")',
    idMeal: "52923",
  },
  {
    strMeal: "Carrot Cake",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52897.jpg")',
    idMeal: "52897",
  },
  {
    strMeal: "Cashew Ghoriba Biscuits",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52976.jpg")',
    idMeal: "52976",
  },
  {
    strMeal: "Chelsea Buns",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52898.jpg")',
    idMeal: "52898",
  },
  {
    strMeal: "Chinon Apple Tarts",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52910.jpg")',
    idMeal: "52910",
  },
  {
    strMeal: "Choc Chip Pecan Pie",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52856.jpg")',
    idMeal: "52856",
  },
  {
    strMeal: "Chocolate Avocado Mousse",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52853.jpg")',
    idMeal: "52853",
  },
  {
    strMeal: "Chocolate Caramel Crispy",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52966.jpg")',
    idMeal: "52966",
  },
  {
    strMeal: "Chocolate Gateau",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52776.jpg")',
    idMeal: "52776",
  },
  {
    strMeal: "Chocolate Raspberry Brownies",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52860.jpg")',
    idMeal: "52860",
  },
  {
    strMeal: "Chocolate Souffle",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52905.jpg")',
    idMeal: "52905",
  },
  {
    strMeal: "Christmas cake",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52990.jpg")',
    idMeal: "52990",
  },
  {
    strMeal: "Christmas Pudding Flapjack",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52788.jpg")',
    idMeal: "52788",
  },
  {
    strMeal: "Christmas Pudding Trifle",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52989.jpg")',
    idMeal: "52989",
  },
  {
    strMeal: "Classic Christmas pudding",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52988.jpg")',
    idMeal: "52988",
  },
  {
    strMeal: "Dundee cake",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52899.jpg")',
    idMeal: "52899",
  },
  {
    strMeal: "Eccles Cakes",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52888.jpg")',
    idMeal: "52888",
  },
  {
    strMeal: "Eton Mess",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52791.jpg")',
    idMeal: "52791",
  },
  {
    strMeal: "Honey Yogurt Cheesecake",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/53007.jpg")',
    idMeal: "53007",
  },
  {
    strMeal: "Hot Chocolate Fudge",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52787.jpg")',
    idMeal: "52787",
  },
  {
    strMeal: "Jam Roly-Poly",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52890.jpg")',
    idMeal: "52890",
  },
  {
    strMeal: "Key Lime Pie",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52859.jpg")',
    idMeal: "52859",
  },
  {
    strMeal: "Krispy Kreme Donut",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/53015.jpg")',
    idMeal: "53015",
  },
  {
    strMeal: "Madeira Cake",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52900.jpg")',
    idMeal: "52900",
  },
  {
    strMeal: "Mince Pies",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52991.jpg")',
    idMeal: "52991",
  },
  {
    strMeal: "Nanaimo Bars",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52924.jpg")',
    idMeal: "52924",
  },
  {
    strMeal: "New York cheesecake",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52858.jpg")',
    idMeal: "52858",
  },
  {
    strMeal: "Pancakes",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52854.jpg")',
    idMeal: "52854",
  },
  {
    strMeal: "Parkin Cake",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52902.jpg")',
    idMeal: "52902",
  },
  {
    strMeal: "Peach & Blueberry Grunt",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52862.jpg")',
    idMeal: "52862",
  },
  {
    strMeal: "Peanut Butter Cheesecake",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52861.jpg")',
    idMeal: "52861",
  },
  {
    strMeal: "Peanut Butter Cookies",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52958.jpg")',
    idMeal: "52958",
  },
  {
    strMeal: "Pear Tarte Tatin",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52916.jpg")',
    idMeal: "52916",
  },
  {
    strMeal: "Polskie Naleśniki (Polish Pancakes)",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/53022.jpg")',
    idMeal: "53022",
  },
  {
    strMeal: "Portuguese custard tarts",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/53046.jpg")',
    idMeal: "53046",
  },
  {
    strMeal: "Pouding chomeur",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52932.jpg")',
    idMeal: "52932",
  },
  {
    strMeal: "Pumpkin Pie",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52857.jpg")',
    idMeal: "52857",
  },
  {
    strMeal: "Rock Cakes",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52901.jpg")',
    idMeal: "52901",
  },
  {
    strMeal: "Rocky Road Fudge",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52786.jpg")',
    idMeal: "52786",
  },
  {
    strMeal: "Rogaliki (Polish Croissant Cookies)",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/53024.jpg")',
    idMeal: "53024",
  },
  {
    strMeal: "Salted Caramel Cheescake",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52833.jpg")',
    idMeal: "52833",
  },
  {
    strMeal: "Seri muka kuih",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/53054.jpg")',
    idMeal: "53054",
  },
  {
    strMeal: "Spotted Dick",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52886.jpg")',
    idMeal: "52886",
  },
  {
    strMeal: "Sticky Toffee Pudding",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52883.jpg")',
    idMeal: "52883",
  },
  {
    strMeal: "Sticky Toffee Pudding Ultimate",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52793.jpg")',
    idMeal: "52793",
  },
  {
    strMeal: "Strawberries Romanoff",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/53082.jpg")',
    idMeal: "53082",
  },
  {
    strMeal: "Strawberry Rhubarb Pie",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/53005.jpg")',
    idMeal: "53005",
  },
  {
    strMeal: "Sugar Pie",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52931.jpg")',
    idMeal: "52931",
  },
  {
    strMeal: "Summer Pudding",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52889.jpg")',
    idMeal: "52889",
  },
  {
    strMeal: "Tarte Tatin",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52909.jpg")',
    idMeal: "52909",
  },
  {
    strMeal: "Timbits",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52929.jpg")',
    idMeal: "52929",
  },
  {
    strMeal: "Treacle Tart",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52892.jpg")',
    idMeal: "52892",
  },
  {
    strMeal: "Tunisian Orange Cake",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52970.jpg")',
    idMeal: "52970",
  },
  {
    strMeal: "Walnut Roll Gužvara",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/53062.jpg")',
    idMeal: "53062",
  },
  {
    strMeal: "White chocolate creme brulee",
    category: "Dessert",
    strMealThumb: 'require("../assets/images/meals/52917.jpg")',
    idMeal: "52917",
  },
  {
    strMeal: "Kapsalon",
    category: "Lamb",
    strMealThumb: 'require("../assets/images/meals/52769.jpg")',
    idMeal: "52769",
  },
  {
    strMeal: "Keleya Zaara",
    category: "Lamb",
    strMealThumb: 'require("../assets/images/meals/52974.jpg")',
    idMeal: "52974",
  },
  {
    strMeal: "Lamb and Lemon Souvlaki",
    category: "Lamb",
    strMealThumb: 'require("../assets/images/meals/53009.jpg")',
    idMeal: "53009",
  },
  {
    strMeal: "Lamb and Potato pie",
    category: "Lamb",
    strMealThumb: 'require("../assets/images/meals/52877.jpg")',
    idMeal: "52877",
  },
  {
    strMeal: "Lamb Biryani",
    category: "Lamb",
    strMealThumb: 'require("../assets/images/meals/52805.jpg")',
    idMeal: "52805",
  },
  {
    strMeal: "Lamb Pilaf (Plov)",
    category: "Lamb",
    strMealThumb: 'require("../assets/images/meals/53083.jpg")',
    idMeal: "53083",
  },
  {
    strMeal: "Lamb Rogan josh",
    category: "Lamb",
    strMealThumb: 'require("../assets/images/meals/52808.jpg")',
    idMeal: "52808",
  },
  {
    strMeal: "Lamb Tagine",
    category: "Lamb",
    strMealThumb: 'require("../assets/images/meals/52843.jpg")',
    idMeal: "52843",
  },
  {
    strMeal: "Lamb tomato and sweet spices",
    category: "Lamb",
    strMealThumb: 'require("../assets/images/meals/52782.jpg")',
    idMeal: "52782",
  },
  {
    strMeal: "Lamb Tzatziki Burgers",
    category: "Lamb",
    strMealThumb: 'require("../assets/images/meals/53010.jpg")',
    idMeal: "53010",
  },
  {
    strMeal: "Lancashire hotpot",
    category: "Lamb",
    strMealThumb: 'require("../assets/images/meals/52884.jpg")',
    idMeal: "52884",
  },
  {
    strMeal: "McSinghs Scotch pie",
    category: "Lamb",
    strMealThumb: 'require("../assets/images/meals/52880.jpg")',
    idMeal: "52880",
  },
  {
    strMeal: "Rigatoni with fennel sausage sauce",
    category: "Lamb",
    strMealThumb: 'require("../assets/images/meals/52783.jpg")',
    idMeal: "52783",
  },
  {
    strMeal: "Stuffed Lamb Tomatoes",
    category: "Lamb",
    strMealThumb: 'require("../assets/images/meals/53008.jpg")',
    idMeal: "53008",
  },
  {
    strMeal: "Tunisian Lamb Soup",
    category: "Lamb",
    strMealThumb: 'require("../assets/images/meals/52972.jpg")',
    idMeal: "52972",
  },
  {
    strMeal: "Bean & Sausage Hotpot",
    category: "Miscellaneous",
    strMealThumb: 'require("../assets/images/meals/52848.jpg")',
    idMeal: "52848",
  },
  {
    strMeal: "Callaloo Jamaican Style",
    category: "Miscellaneous",
    strMealThumb: 'require("../assets/images/meals/52939.jpg")',
    idMeal: "52939",
  },
  {
    strMeal: "Chakchouka ",
    category: "Miscellaneous",
    strMealThumb: 'require("../assets/images/meals/52969.jpg")',
    idMeal: "52969",
  },
  {
    strMeal: "Duck Confit",
    category: "Miscellaneous",
    strMealThumb: 'require("../assets/images/meals/52907.jpg")',
    idMeal: "52907",
  },
  {
    strMeal: "French Lentils With Garlic and Thyme",
    category: "Miscellaneous",
    strMealThumb: 'require("../assets/images/meals/52815.jpg")',
    idMeal: "52815",
  },
  {
    strMeal: "French Omelette",
    category: "Miscellaneous",
    strMealThumb: 'require("../assets/images/meals/52915.jpg")',
    idMeal: "52915",
  },
  {
    strMeal: "Osso Buco alla Milanese",
    category: "Miscellaneous",
    strMealThumb: 'require("../assets/images/meals/52810.jpg")',
    idMeal: "52810",
  },
  {
    strMeal: "Pizza Express Margherita",
    category: "Miscellaneous",
    strMealThumb: 'require("../assets/images/meals/53014.jpg")',
    idMeal: "53014",
  },
  {
    strMeal: "Poutine",
    category: "Miscellaneous",
    strMealThumb: 'require("../assets/images/meals/52804.jpg")',
    idMeal: "52804",
  },
  {
    strMeal: "Three-cheese souffles",
    category: "Miscellaneous",
    strMealThumb: 'require("../assets/images/meals/52912.jpg")',
    idMeal: "52912",
  },
  {
    strMeal: "Turkey Meatloaf",
    category: "Miscellaneous",
    strMealThumb: 'require("../assets/images/meals/52845.jpg")',
    idMeal: "52845",
  },

  {
    strMeal: "Chilli prawn linguine",
    category: "Pasta",
    strMealThumb: 'require("../assets/images/meals/52839.jpg")',
    idMeal: "52839",
  },
  {
    strMeal: "Fettuccine Alfredo",
    category: "Pasta",
    strMealThumb: 'require("../assets/images/meals/53064.jpg")',
    idMeal: "53064",
  },
  {
    strMeal: "Fettucine alfredo",
    category: "Pasta",
    strMealThumb: 'require("../assets/images/meals/52835.jpg")',
    idMeal: "52835",
  },
  {
    strMeal: "Grilled Mac and Cheese Sandwich",
    category: "Pasta",
    strMealThumb: 'require("../assets/images/meals/52829.jpg")',
    idMeal: "52829",
  },
  {
    strMeal: "Lasagna Sandwiches",
    category: "Pasta",
    strMealThumb: 'require("../assets/images/meals/52987.jpg")',
    idMeal: "52987",
  },
  {
    strMeal: "Lasagne",
    category: "Pasta",
    strMealThumb: 'require("../assets/images/meals/52844.jpg")',
    idMeal: "52844",
  },
  {
    strMeal: "Pilchard puttanesca",
    category: "Pasta",
    strMealThumb: 'require("../assets/images/meals/52837.jpg")',
    idMeal: "52837",
  },
  {
    strMeal: "Spaghetti alla Carbonara",
    category: "Pasta",
    strMealThumb: 'require("../assets/images/meals/52982.jpg")',
    idMeal: "52982",
  },
  {
    strMeal: "Venetian Duck Ragu",
    category: "Pasta",
    strMealThumb: 'require("../assets/images/meals/52838.jpg")',
    idMeal: "52838",
  },
  {
    strMeal: " Bubble & Squeak",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/52885.jpg")',
    idMeal: "52885",
  },
  {
    strMeal: "BBQ Pork Sloppy Joes",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/52995.jpg")',
    idMeal: "52995",
  },
  {
    strMeal: "Bigos (Hunters Stew)",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/53018.jpg")',
    idMeal: "53018",
  },
  {
    strMeal: "Boxty Breakfast",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/53036.jpg")',
    idMeal: "53036",
  },
  {
    strMeal: "Coddled pork with cider",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/53037.jpg")',
    idMeal: "53037",
  },
  {
    strMeal: "Crispy Sausages and Greens",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/52999.jpg")',
    idMeal: "52999",
  },
  {
    strMeal: "Ham hock colcannon",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/53035.jpg")',
    idMeal: "53035",
  },
  {
    strMeal: "Hot and Sour Soup",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/52954.jpg")',
    idMeal: "52954",
  },
  {
    strMeal: "Japanese Katsudon",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/53034.jpg")',
    idMeal: "53034",
  },
  {
    strMeal: "Pork Cassoulet",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/52847.jpg")',
    idMeal: "52847",
  },
  {
    strMeal: "Portuguese barbecued pork (Febras assadas)",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/53044.jpg")',
    idMeal: "53044",
  },
  {
    strMeal: "Skillet Apple Pork Chops with Roasted Sweet Potatoes & Zucchini",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/52994.jpg")',
    idMeal: "52994",
  },
  {
    strMeal: "Stamppot",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/52980.jpg")',
    idMeal: "52980",
  },
  {
    strMeal: "Sweet and Sour Pork",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/52949.jpg")',
    idMeal: "52949",
  },
  {
    strMeal: "Toad In The Hole",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/52822.jpg")',
    idMeal: "52822",
  },
  {
    strMeal: "Tonkatsu pork",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/53032.jpg")',
    idMeal: "53032",
  },
  {
    strMeal: "Tourtiere",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/52926.jpg")',
    idMeal: "52926",
  },
  {
    strMeal: "Vietnamese Grilled Pork (bun-thit-nuong)",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/52828.jpg")',
    idMeal: "52828",
  },
  {
    strMeal: "Wontons",
    category: "Pork",
    strMealThumb: 'require("../assets/images/meals/52948.jpg")',
    idMeal: "52948",
  },
  {
    strMeal: "Baked salmon with fennel & tomatoes",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52959.jpg")',
    idMeal: "52959",
  },
  {
    strMeal: "Cajun spiced fish tacos",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52819.jpg")',
    idMeal: "52819",
  },
  {
    strMeal: "Escovitch Fish",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52944.jpg")',
    idMeal: "52944",
  },
  {
    strMeal: "Fish fofos",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/53043.jpg")',
    idMeal: "53043",
  },
  {
    strMeal: "Fish pie",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52802.jpg")',
    idMeal: "52802",
  },
  {
    strMeal: "Fish Soup (Ukha)",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/53079.jpg")',
    idMeal: "53079",
  },
  {
    strMeal: "Fish Stew with Rouille",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52918.jpg")',
    idMeal: "52918",
  },
  {
    strMeal: "Garides Saganaki",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52764.jpg")',
    idMeal: "52764",
  },
  {
    strMeal: "Grilled Portuguese sardines",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/53041.jpg")',
    idMeal: "53041",
  },
  {
    strMeal: "Honey Teriyaki Salmon",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52773.jpg")',
    idMeal: "52773",
  },
  {
    strMeal: "Kedgeree",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52887.jpg")',
    idMeal: "52887",
  },
  {
    strMeal: "Kung Po Prawns",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52946.jpg")',
    idMeal: "52946",
  },
  {
    strMeal: "Laksa King Prawn Noodles",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52821.jpg")',
    idMeal: "52821",
  },
  {
    strMeal: "Mediterranean Pasta Salad",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52777.jpg")',
    idMeal: "52777",
  },
  {
    strMeal: "Mee goreng mamak",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/53048.jpg")',
    idMeal: "53048",
  },
  {
    strMeal: "Nasi lemak",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/53051.jpg")',
    idMeal: "53051",
  },
  {
    strMeal: "Portuguese fish stew (Caldeirada de peixe)",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/53045.jpg")',
    idMeal: "53045",
  },
  {
    strMeal: "Recheado Masala Fish",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52809.jpg")',
    idMeal: "52809",
  },
  {
    strMeal: "Salmon Avocado Salad",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52960.jpg")',
    idMeal: "52960",
  },
  {
    strMeal: "Salmon Prawn Risotto",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52823.jpg")',
    idMeal: "52823",
  },
  {
    strMeal: "Saltfish and Ackee",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52936.jpg")',
    idMeal: "52936",
  },
  {
    strMeal: "Seafood fideuà",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52836.jpg")',
    idMeal: "52836",
  },
  {
    strMeal: "Shrimp Chow Fun",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52953.jpg")',
    idMeal: "52953",
  },
  {
    strMeal: "Sledz w Oleju (Polish Herrings)",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/53023.jpg")',
    idMeal: "53023",
  },
  {
    strMeal: "Spring onion and prawn empanadas",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/53040.jpg")',
    idMeal: "53040",
  },
  {
    strMeal: "Sushi",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/53065.jpg")',
    idMeal: "53065",
  },
  {
    strMeal: "Three Fish Pie",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52882.jpg")',
    idMeal: "52882",
  },
  {
    strMeal: "Tuna and Egg Briks",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52975.jpg")',
    idMeal: "52975",
  },
  {
    strMeal: "Tuna Nicoise",
    category: "Seafood",
    strMealThumb: 'require("../assets/images/meals/52852.jpg")',
    idMeal: "52852",
  },
  {
    strMeal: "Blini Pancakes",
    category: "Side",
    strMealThumb: 'require("../assets/images/meals/53080.jpg")',
    idMeal: "53080",
  },
  {
    strMeal: "Boulangère Potatoes",
    category: "Side",
    strMealThumb: 'require("../assets/images/meals/52914.jpg")',
    idMeal: "52914",
  },
  {
    strMeal: "Brie wrapped in prosciutto & brioche",
    category: "Side",
    strMealThumb: 'require("../assets/images/meals/52913.jpg")',
    idMeal: "52913",
  },
  {
    strMeal: "Burek",
    category: "Side",
    strMealThumb: 'require("../assets/images/meals/53060.jpg")',
    idMeal: "53060",
  },
  {
    strMeal: "Corba",
    category: "Side",
    strMealThumb: 'require("../assets/images/meals/52977.jpg")',
    idMeal: "52977",
  },
  {
    strMeal: "Fennel Dauphinoise",
    category: "Side",
    strMealThumb: 'require("../assets/images/meals/52919.jpg")',
    idMeal: "52919",
  },
  {
    strMeal: "Feteer Meshaltet",
    category: "Side",
    strMealThumb: 'require("../assets/images/meals/53030.jpg")',
    idMeal: "53030",
  },
  {
    strMeal: "French Onion Soup",
    category: "Side",
    strMealThumb: 'require("../assets/images/meals/52903.jpg")',
    idMeal: "52903",
  },
  {
    strMeal: "Fresh sardines",
    category: "Side",
    strMealThumb: 'require("../assets/images/meals/53061.jpg")',
    idMeal: "53061",
  },
  {
    strMeal: "Japanese gohan rice",
    category: "Side",
    strMealThumb: 'require("../assets/images/meals/53033.jpg")',
    idMeal: "53033",
  },
  {
    strMeal: "Kumpir",
    category: "Side",
    strMealThumb: 'require("../assets/images/meals/52978.jpg")',
    idMeal: "52978",
  },
  {
    strMeal: "Mushroom soup with buckwheat",
    category: "Side",
    strMealThumb: 'require("../assets/images/meals/53059.jpg")',
    idMeal: "53059",
  },
  {
    strMeal: "Mustard champ",
    category: "Side",
    strMealThumb: 'require("../assets/images/meals/53038.jpg")',
    idMeal: "53038",
  },
  {
    strMeal: "Pierogi (Polish Dumplings)",
    category: "Side",
    strMealThumb: 'require("../assets/images/meals/53019.jpg")',
    idMeal: "53019",
  },
  {
    strMeal: "Prawn & Fennel Bisque",
    category: "Side",
    strMealThumb: 'require("../assets/images/meals/52922.jpg")',
    idMeal: "52922",
  },
  {
    strMeal: "Snert (Dutch Split Pea Soup)",
    category: "Side",
    strMealThumb: 'require("../assets/images/meals/52981.jpg")',
    idMeal: "52981",
  },
  {
    strMeal: "Split Pea Soup",
    category: "Side",
    strMealThumb: 'require("../assets/images/meals/52925.jpg")',
    idMeal: "52925",
  },
  {
    strMeal: "Broccoli & Stilton soup",
    category: "Starter",
    strMealThumb: 'require("../assets/images/meals/52842.jpg")',
    idMeal: "52842",
  },
  {
    strMeal: "Clam chowder",
    category: "Starter",
    strMealThumb: 'require("../assets/images/meals/52840.jpg")',
    idMeal: "52840",
  },
  {
    strMeal: "Cream Cheese Tart",
    category: "Starter",
    strMealThumb: 'require("../assets/images/meals/52779.jpg")',
    idMeal: "52779",
  },
  {
    strMeal: "Creamy Tomato Soup",
    category: "Starter",
    strMealThumb: 'require("../assets/images/meals/52841.jpg")',
    idMeal: "52841",
  },

  {
    strMeal: "Roast fennel and aubergine paella",
    category: "Vegan",
    strMealThumb: 'require("../assets/images/meals/52942.jpg")',
    idMeal: "52942",
  },
  {
    strMeal: "Vegan Chocolate Cake",
    category: "Vegan",
    strMealThumb: 'require("../assets/images/meals/52794.jpg")',
    idMeal: "52794",
  },
  {
    strMeal: "Vegan Lasagna",
    category: "Vegan",
    strMealThumb: 'require("../assets/images/meals/52775.jpg")',
    idMeal: "52775",
  },

  {
    strMeal: "Baingan Bharta",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52807.jpg")',
    idMeal: "52807",
  },
  {
    strMeal: "Beetroot Soup (Borscht)",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/53078.jpg")',
    idMeal: "53078",
  },
  {
    strMeal: "Cabbage Soup (Shchi)",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/53077.jpg")',
    idMeal: "53077",
  },
  {
    strMeal: "Chickpea Fajitas",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52870.jpg")',
    idMeal: "52870",
  },
  {
    strMeal: "Crispy Eggplant",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/53072.jpg")',
    idMeal: "53072",
  },
  {
    strMeal: "Dal fry",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52785.jpg")',
    idMeal: "52785",
  },
  {
    strMeal: "Egg Drop Soup",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52955.jpg")',
    idMeal: "52955",
  },
  {
    strMeal: "Eggplant Adobo",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/53073.jpg")',
    idMeal: "53073",
  },
  {
    strMeal: "Flamiche",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52906.jpg")',
    idMeal: "52906",
  },
  {
    strMeal: "Ful Medames",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/53025.jpg")',
    idMeal: "53025",
  },
  {
    strMeal: "Gigantes Plaki",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/53012.jpg")',
    idMeal: "53012",
  },
  {
    strMeal: "Grilled eggplant with coconut milk",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/53074.jpg")',
    idMeal: "53074",
  },
  {
    strMeal: "Kafteji",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52971.jpg")',
    idMeal: "52971",
  },
  {
    strMeal: "Kidney Bean Curry",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52868.jpg")',
    idMeal: "52868",
  },
  {
    strMeal: "Koshari",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/53027.jpg")',
    idMeal: "53027",
  },
  {
    strMeal: "Leblebi Soup",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52973.jpg")',
    idMeal: "52973",
  },
  {
    strMeal: "Matar Paneer",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52865.jpg")',
    idMeal: "52865",
  },
  {
    strMeal: "Moroccan Carrot Soup",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/53047.jpg")',
    idMeal: "53047",
  },
  {
    strMeal: "Mushroom & Chestnut Rotolo",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52864.jpg")',
    idMeal: "52864",
  },
  {
    strMeal: "Potato Salad (Olivier Salad)",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/53081.jpg")',
    idMeal: "53081",
  },
  {
    strMeal: "Provençal Omelette Cake",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52921.jpg")',
    idMeal: "52921",
  },
  {
    strMeal: "Ratatouille",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52908.jpg")',
    idMeal: "52908",
  },
  {
    strMeal: "Ribollita",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52811.jpg")',
    idMeal: "52811",
  },
  {
    strMeal: "Roasted Eggplant With Tahini, Pine Nuts, and Lentils",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52816.jpg")',
    idMeal: "52816",
  },
  {
    strMeal: "Shakshuka",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52963.jpg")',
    idMeal: "52963",
  },
  {
    strMeal: "Smoky Lentil Chili with Squash",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52784.jpg")',
    idMeal: "52784",
  },
  {
    strMeal: "Spanish Tortilla",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52872.jpg")',
    idMeal: "52872",
  },
  {
    strMeal: "Spicy Arrabiata Penne",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52771.jpg")',
    idMeal: "52771",
  },
  {
    strMeal: "Spicy North African Potato Salad",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52797.jpg")',
    idMeal: "52797",
  },
  {
    strMeal: "Spinach & Ricotta Cannelloni",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52849.jpg")',
    idMeal: "52849",
  },
  {
    strMeal: "Squash linguine",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52866.jpg")',
    idMeal: "52866",
  },
  {
    strMeal: "Stovetop Eggplant With Harissa, Chickpeas, and Cumin Yogurt",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52817.jpg")',
    idMeal: "52817",
  },
  {
    strMeal: "Stuffed Bell Peppers with Quinoa and Black Beans",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/53067.jpg")',
    idMeal: "53067",
  },
  {
    strMeal: "Summer Pistou",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52911.jpg")',
    idMeal: "52911",
  },
  {
    strMeal: "Tahini Lentils",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52869.jpg")',
    idMeal: "52869",
  },
  {
    strMeal: "Tamiya",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/53026.jpg")',
    idMeal: "53026",
  },
  {
    strMeal: "Tortang Talong",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/53075.jpg")',
    idMeal: "53075",
  },
  {
    strMeal: "Vegetarian Casserole",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52863.jpg")',
    idMeal: "52863",
  },
  {
    strMeal: "Vegetarian Chilli",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52867.jpg")',
    idMeal: "52867",
  },
  {
    strMeal: "Yaki Udon",
    category: "Vegetarian",
    strMealThumb: 'require("../assets/images/meals/52871.jpg")',
    idMeal: "52871",
  },
  {
    strMeal: "Bread omelette",
    category: "Breakfast",
    strMealThumb: 'require("../assets/images/meals/53076.jpg")',
    idMeal: "53076",
  },
  {
    strMeal: "Breakfast Potatoes",
    category: "Breakfast",
    strMealThumb: 'require("../assets/images/meals/52965.jpg")',
    idMeal: "52965",
  },
  {
    strMeal: "English Breakfast",
    category: "Breakfast",
    strMealThumb: 'require("../assets/images/meals/52895.jpg")',
    idMeal: "52895",
  },
  {
    strMeal: "Fruit and Cream Cheese Breakfast Pastries",
    category: "Breakfast",
    strMealThumb: 'require("../assets/images/meals/52957.jpg")',
    idMeal: "52957",
  },
  {
    strMeal: "Full English Breakfast",
    category: "Breakfast",
    strMealThumb: 'require("../assets/images/meals/52896.jpg")',
    idMeal: "52896",
  },
  {
    strMeal: "Home-made Mandazi",
    category: "Breakfast",
    strMealThumb: 'require("../assets/images/meals/52967.jpg")',
    idMeal: "52967",
  },
  {
    strMeal: "Salmon Eggs Eggs Benedict",
    category: "Breakfast",
    strMealThumb: 'require("../assets/images/meals/52962.jpg")',
    idMeal: "52962",
  },
  {
    strMeal: "Smoked Haddock Kedgeree",
    category: "Breakfast",
    strMealThumb: 'require("../assets/images/meals/52964.jpg")',
    idMeal: "52964",
  },
  {
    strMeal: "Mbuzi Choma (Roasted Goat)",
    category: "Goat",
    strMealThumb: 'require("../assets/images/meals/52968.jpg")',
    idMeal: "52968",
  },
];
